chore: Disable miri check in CI
This has started failing:

>    Doc-tests ffi_patterns
> fatal error: cross-interpreting doctests is not currently supported by Miri.
> error: doctest failed, to rerun pass `-p ffi_patterns --doc`

That the results change is not completely unexpected since miri uses
nigthly and we don't pin nightly because I don't know how.