chore: Pin nightly (#191)
Because `check_miri` started failing:

>    Doc-tests ffi_patterns
> fatal error: cross-interpreting doctests is not currently supported
> by Miri.
> error: doctest failed, to rerun pass `-p ffi_patterns --doc`

This seems to work for now, but I have a vague memory of a pinned
nightly stopping working for me in the past. If this happens, we
should consider disabling the failing test in CI.